# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, allTest ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew compileJava allTest
    - name: Upload Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: test-results-${{ github.run_id }}
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          build/test-results
          build/reports
        if-no-files-found: error
        retention-days: 3